#include<concepts>
#include<coroutine>
#include<any>
#include<bitset>
#include<chrono>
#include<compare>
#include<csetjmp>
#include<csignal>
#include<cstdarg>
#include<cstddef>
#include<cstdlib>
#include<ctime>
#ifdef __cpp_lib_debugging
#include<debugging>
#endif
#include<expected>
#include<functional>
#include<initializer_list>
#include<optional>
#include<source_location>
#include<tuple>
#include<type_traits>
#include<typeindex>
#include<typeinfo>
#include<utility>
#include<variant>
#include<version>
#include<memory>
#include<memory_resource>
#include<new>
#include<scoped_allocator>
#include<cfloat>
#include<cinttypes>
#include<climits>
#include<cstdint>
#include<limits>
#include<stdfloat>
#include<cassert>
#include<cerrno>
#include<exception>
#include<stacktrace>
#include<stdexcept>
#include<system_error>
#include<cctype>
#include<charconv>
#include<cstring>
#include<cuchar>
#include<cwchar>
#include<cwctype>
#include<format>
#include<string>
#include<string_view>
#include<array>
#include<deque>
#ifdef __cpp_lib_flat_map
#include<flat_map>
#endif
#ifdef __cpp_lib_flat_set
#include<flat_set>
#endif	
#include<forward_list>
#include<list>
#include<map>
#ifdef __cpp_lib_mdspan
#include<mdspan>
#endif
#include<queue>
#include<set>
#include<span>
#include<stack>
#include<unordered_map>
#include<unordered_set>
#include<vector>
#include<iterator>
#ifdef __cpp_lib_generator
#include<generator>
#endif
#include<ranges>
#include<algorithm>
#include<execution>
#include<bit>
#include<cfenv>
#include<cmath>
#include<complex>
#ifdef __cpp_lib_linalg
#include<linalg>
#endif
#include<numbers>
#include<numeric>
#include<random>
#include<ratio>
#include<valarray>
#include<clocale>
#include<codecvt>
#include<locale>
#ifdef __cpp_lib_text_encoding
#include<text_encoding>
#endif
#include<cstdio>
#include<fstream>
#include<iomanip>
#include<ios>
#include<iosfwd>
#include<iostream>
#include<istream>
#include<ostream>
#ifdef __cpp_lib_print
#include<print>
#endif
#include<spanstream>
#include<sstream>
#include<streambuf>
#include<syncstream>
#include<filesystem>
#include<regex>
#include<atomic>
#include<barrier>
#include<condition_variable>
#include<future>
#ifdef __cpp_lib_hazard_pointer
#include<hazard_pointer>
#endif
#include<latch>
#include<mutex>
#ifdef __cpp_lib_rcu
#include<rcu>
#endif
#include<semaphore>
#include<shared_mutex>
#include<stop_token>
#include<thread>